# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/earth/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),earth)

$(call add-radio-file-sha1-checked,radio/gz.img,c2c68f3e34236641e9a093e2de322b584c725f5a)
$(call add-radio-file-sha1-checked,radio/lk.img,db0cc2715f65293da14926b060749147a93bcbbb)
$(call add-radio-file-sha1-checked,radio/logo.img,4de81eec5af850d466d8f276c52f17c7ce9470d0)
$(call add-radio-file-sha1-checked,radio/md1img.img,e4318fa684a47c4334808dabbffeed74991318d5)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,95aa2ac5dbc28d2f3c8ac6429517069d25c56d17)
$(call add-radio-file-sha1-checked,radio/scp.img,524c9a62b21ccc69aece8b579f0ce25bc367dd5e)
$(call add-radio-file-sha1-checked,radio/spmfw.img,807e3110a964c5baecebd4f81c6b81f6acd961b1)
$(call add-radio-file-sha1-checked,radio/sspm.img,a183fe520ee1927632ba585b074bdffb3d699a7d)
$(call add-radio-file-sha1-checked,radio/tee.img,4086c2afbe010a848ef577bf8a2fa7b9f3c001fd)

endif
